#ifndef IOT_02_MQTT_TOPICS
#define IOT_02_MQTT_TOPICS

#define TOPIC_REQUEST_MAC "/macReq"
#define TOPIC_MAC "/mac"
#define TOPIC_LED_W "/ledW"
#define TOPIC_LED_R "/ledR"
#define TOPIC_LED_Y "/ledY"
#define TOPIC_LED_G "/ledG"
#define TOPIC_LATCHING_RELAY "/latchingRelay"
#define TOPIC_BT_IO0 "/btIO0"
#define TOPIC_BT_I34 "/btI34"
#define TOPIC_BT_I35 "/btI35"
#define TOPIC_LATCHING_RELAY_STATE "/latchingRelayState"
#define TOPIC_REQUEST_LATCHING_RELAY_STATE "/latchingRelayStateReq"
#define TOPIC_REQUEST_LDR "/ldrReq"
#define TOPIC_LDR "/ldr"
#define TOPIC_REQUEST_T "/tempReq"
#define TOPIC_T "/temp"
#define TOPIC_REQUEST_RH "/rhReq"
#define TOPIC_RH "/rh"
#define TOPIC_REQUEST_P "/pressureReq"
#define TOPIC_P "/pressure"
#define TOPIC_REQUEST_ALT "/altitudeReq"
#define TOPIC_ALT "/altitude"
#define TOPIC_SMALL_TEXT "/10pxTxt"
#define TOPIC_MEDIUM_TEXT "/16pxTxt"
#define TOPIC_BIG_TEXT "/24pxTxt"
#define TOPIC_JSON_DATA "/jsData"

#endif // IOT_02_MQTT_TOPICS
